trigger:
  - develop

variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    environment: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo $(system.pullRequest.sourceBranch) / $(system.pullRequest.targetBranch)
              displayName: 'Run a system.pullRequest.sourceBranch'