variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    variables:
      - name: targetBranch
        value: echo $(system.pullRequest.targetBranch)
      - name: sourceBranch
        value: echo $(system.pullRequest.sourceBranch)
    environment: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo run from $(system.pullRequest.sourceBranch) into $(system.pullRequest.targetBranch)
              displayName: s'Run a $(system.pullRequest.sourceBranch)'