# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#resources:
#  repositories:
#    - repository: common
#      type: github
#      name: Contoso/CommonTools
#      endpoint: MyContosoServiceConnection
#      trigger:
#        branches:
#          include:
#            - develop
trigger:
  - develop

variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    environment: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: ${sourceBranch}!
              displayName: 'Run a ${sourceBranch} '
            - script: ${targetBranch}!
              displayName: 'Run a ${targetBranch}'
            - script: $(sourceBranch) !
              displayName: 'Run a $(sourceBranch)'
            - script: $(targetBranch) !
              displayName: 'Run a $(targetBranch)'
            - script: $(pullRequest.targetBranch) !
              displayName: 'Run a $(pullRequest.targetBranch)'
            - script: ${pullRequest.targetBranch} !
              displayName: 'Run a ${pullRequest.targetBranch}'
            - script: ${system.pullRequest.targetBranch} !
              displayName: 'Run a ${system.pullRequest.targetBranch}'
            - script: $(system.pullRequest.targetBranch) !
              displayName: 'Run a $(system.pullRequest.targetBranch)'