# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#resources:
#  repositories:
#    - repository: common
#      type: github
#      name: Contoso/CommonTools
#      endpoint: MyContosoServiceConnection
#      trigger:
#        branches:
#          include:
#            - develop
trigger:
  - develop

variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    environment: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
            - script: $(pullRequest.sourceBranch ) !
              displayName: 'Run a $(pullRequest.sourceBranch )'
            - script: ${pullRequest.targetBranch} !
              displayName: 'Run a ${pullRequest.targetBranch}'
            - script: ${system.pullRequest.sourceBranch } !
              displayName: 'Run a ${system.pullRequest.sourceBranch }'
            - script: $(system.pullRequest.targetBranch) !
              displayName: 'Run a $(system.pullRequest.targetBranch)'