variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    variables:
      - name: targetBranch
        value: echo $(system.pullRequest.targetBranch)
      - name: sourceBranch
        value: echo $(system.pullRequest.sourceBranch)
    environment: DEV1
    strategy:
      runOnce:
        deploy:
          steps:
            - template: jobs/build.yml