variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
            - template: jobs/build.yml