variables:
  - name: vmImage
    value: 'ubuntu-latest'

jobs:
  - deployment: ValidateJob
    pool:
      vmImage: $(vmImage)
    environment: DEV
    strategy:
      runOnce:
        deploy:
          - template: jobs/build.yml
#          steps:
#            - script: git merge origin/feature/* echo run from $(system.pullRequest.sourceBranch) into $(system.pullRequest.targetBranch)
#              displayName: 'Run a system.pullRequest.sourceBranch'